# This turns the whole config file on or off, if "false" none of the blacklists function.
enabled: true

# This determines if a player in LC can damage entities or not
player-damage-entities: false

# Glowing Effect or Armor? true for Glowing, false for Armor
glowing: true

# Specify which blocks are able to be placed
blacklisted-blocks:
- air

#Specify what inventories and blocks can be interacted with (right-clicked)
blacklisted-interactables:
- air

# Specify what entities can't be spawned through creative mode
blacklisted-entities:
- air

#Specify what blocks cannot be broken while in LC
blacklisted-breakables:
- air