enabled: true
blacklisted-blocks:
  - diamond_block
  - netherite_block
  - emerald_block
  - hay_block
blacklisted-interactables:
  - chest
  - hopper
  - trapped_chest
  - furnace
blacklisted-entities:
  - minecart
  - tnt_minecart
  - furnace_minecart