main: me.Adelemphii.LimitedCreative.Main
name: LimitedCreative
version: 1.1
api-version: 1.13
author: Adelemphii

commands:
  LimitedCreative:
    aliases: lc
    description: Using /lc or /lc <Username> allows you to give LimitedCreative to yourself or another player.
    permission: limitedcreative